#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
WAF/CDN Detector - Header fingerprinting, malformed request, ASN check
"""

import re
import json
import logging
import requests
from typing import Dict, List
from pathlib import Path

from PyQt6.QtCore import QThread, pyqtSignal, Qt
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QLineEdit,
    QGroupBox, QProgressBar, QLabel, QTableWidget, QTableWidgetItem,
    QHeaderView, QTextEdit, QFileDialog, QMessageBox
)

logger = logging.getLogger(__name__)


class WAFDetectWorker(QThread):
    progress = pyqtSignal(int, str)
    result = pyqtSignal(dict)
    error = pyqtSignal(str)
    finished_signal = pyqtSignal()   # ← إضافة الإشارة

    def __init__(self, target: str):
        super().__init__()
        self.target = target
        self._abort = False
        self.session = requests.Session()

    def abort(self):
        self._abort = True
        self.session.close()

    def ensure_signatures(self):
        sig_path = Path(__file__).parent.parent.parent / "data" / "waf_signatures.json"
        sig_path.parent.mkdir(parents=True, exist_ok=True)
        if not sig_path.exists():
            default = {
                "Cloudflare": {"headers": ["CF-RAY", "cf-cache-status"], "cookies": ["__cflb", "__cfduid"], "server": ["cloudflare"], "body_patterns": []},
                "Sucuri": {"headers": ["X-Sucuri-ID", "X-Sucuri-Cache"], "cookies": [], "server": ["Sucuri/Cloudproxy"], "body_patterns": []},
                "ModSecurity": {"headers": ["X-Mod-Security-Active"], "cookies": [], "server": [], "body_patterns": ["ModSecurity", "This error was generated by Mod_Security"]},
                "Imperva": {"headers": ["X-Iinfo"], "cookies": ["incap_ses", "visid_incap"], "server": [], "body_patterns": []},
                "Akamai": {"headers": ["X-Check-Cacheable", "Akamai-Cache-Status"], "cookies": [], "server": ["AkamaiGHost"], "body_patterns": []},
                "AWS CloudFront": {"headers": ["X-Amz-Cf-Id", "X-Amz-Cf-Pop"], "cookies": [], "server": ["CloudFront"], "body_patterns": []},
                "F5 BIG-IP": {"headers": ["X-WA-Info"], "cookies": ["BIGipServer", "TS0"], "server": [], "body_patterns": []},
                "Fastly CDN": {"headers": ["X-Served-By", "X-Cache-Hits", "Fastly-Restarts"], "cookies": [], "server": [], "body_patterns": []},
                "Azure Front Door": {"headers": ["X-Azure-Ref", "X-FD-HealthProbe"], "cookies": [], "server": [], "body_patterns": []}
            }
            sig_path.write_text(json.dumps(default, indent=2))
        tips_path = Path(__file__).parent.parent.parent / "data" / "evasion_tips.json"
        if not tips_path.exists():
            default_tips = {
                "Cloudflare": "Use IP rotation, try different encoding (double URL encoding), or use API endpoints that may not be protected.",
                "ModSecurity": "Use case transformation, add junk data to bypass regex rules, or use SQL injection with hex encoding.",
                "Sucuri": "Try using HTTP methods other than GET/POST, or add parameter pollution.",
                "Imperva": "Use slow requests, or try to bypass with path traversal tricks.",
                "Akamai": "Try to use mobile user agents or different TLS ciphers.",
                "AWS CloudFront": "Use origin IP discovery via historical DNS records.",
                "Fastly CDN": "Use variant encoding, or find unprotected staging domains.",
                "F5 BIG-IP": "Use parameter name fuzzing to find unprotected parameters.",
                "Azure Front Door": "Try using different host headers or IP spoofing techniques."
            }
            tips_path.write_text(json.dumps(default_tips, indent=2))

    def load_signatures(self) -> Dict:
        self.ensure_signatures()
        sig_path = Path(__file__).parent.parent.parent / "data" / "waf_signatures.json"
        with open(sig_path) as f:
            return json.load(f)

    def load_evasion_tips(self) -> Dict:
        tips_path = Path(__file__).parent.parent.parent / "data" / "evasion_tips.json"
        with open(tips_path) as f:
            return json.load(f)

    def get_resolved_ip(self, domain: str) -> str:
        try:
            import socket
            return socket.gethostbyname(domain.split('/')[0])
        except:
            return ""

    def get_asn_info(self, ip: str) -> Dict:
        try:
            resp = requests.get(f"http://ip-api.com/json/{ip}", timeout=5)
            if resp.status_code == 200:
                data = resp.json()
                return {'as': data.get('as', ''), 'org': data.get('org', '')}
        except:
            pass
        return {}

    def run(self):
        try:
            self.ensure_signatures()
            signatures = self.load_signatures()
            evasion_tips = self.load_evasion_tips()
            self.progress.emit(20, "Sending baseline request...")
            resp = self.session.get(self.target, timeout=15, allow_redirects=True)

            self.progress.emit(40, "Analyzing headers and cookies...")
            waf_scores = {}
            for waf_name, data in signatures.items():
                score = 0
                indicators = []
                for header in data.get('headers', []):
                    if header in resp.headers:
                        score += 40
                        indicators.append(f"Header: {header}")
                for cookie in data.get('cookies', []):
                    if any(cookie in c for c in resp.headers.get('Set-Cookie', '')):
                        score += 30
                        indicators.append(f"Cookie: {cookie}")
                server = resp.headers.get('Server', '')
                for srv in data.get('server', []):
                    if srv.lower() in server.lower():
                        score += 40
                        indicators.append(f"Server: {server}")
                for pattern in data.get('body_patterns', []):
                    if re.search(pattern, resp.text, re.IGNORECASE):
                        score += 20
                        indicators.append(f"Body pattern: {pattern}")
                if score > 0:
                    waf_scores[waf_name] = (score, indicators)

            self.progress.emit(60, "Sending malformed request...")
            mal_url = self.target + "/?test=<script>alert(1)</script>&id=1'OR'1'='1"
            mal_resp = self.session.get(mal_url, timeout=15)
            if mal_resp.status_code in (403, 406, 400):
                body_lower = mal_resp.text.lower()
                for waf_name, data in signatures.items():
                    for pattern in data.get('body_patterns', []):
                        if re.search(pattern, body_lower, re.IGNORECASE):
                            old_score, indicators = waf_scores.get(waf_name, (0, []))
                            waf_scores[waf_name] = (old_score + 20, indicators + [f"Malformed request trigger"])

            self.progress.emit(80, "Checking CDN via ASN...")
            ip = self.get_resolved_ip(self.target)
            cdn_provider = "Unknown"
            if ip:
                asn_info = self.get_asn_info(ip)
                known_cdns = {'AS13335': 'Cloudflare', 'AS20940': 'Akamai', 'AS54113': 'Fastly',
                              'AS16509': 'AWS CloudFront', 'AS16625': 'AWS CloudFront', 'AS14618': 'AWS CloudFront'}
                asn = asn_info.get('as')
                if asn in known_cdns:
                    cdn_provider = known_cdns[asn]
                    if cdn_provider in waf_scores:
                        old_score, indicators = waf_scores[cdn_provider]
                        waf_scores[cdn_provider] = (old_score + 50, indicators + [f"ASN match: {asn}"])

            self.progress.emit(90, "Calculating confidence...")
            best_waf = "None Detected"
            best_score = 0
            best_indicators = []
            for waf_name, (score, indicators) in waf_scores.items():
                if score > best_score:
                    best_score = score
                    best_waf = waf_name
                    best_indicators = indicators
            confidence = min(best_score, 100)
            if confidence >= 70:
                verdict = "Confirmed"
            elif confidence >= 40:
                verdict = "Likely"
            else:
                verdict = "Unknown"
                best_waf = "None Detected"

            tips = evasion_tips.get(best_waf if best_waf != "None Detected" else "", "No specific tips available.")

            result = {
                'waf_name': best_waf,
                'cdn': cdn_provider,
                'confidence': confidence,
                'verdict': verdict,
                'indicators': best_indicators,
                'evasion_tips': tips,
                'ip': ip
            }
            self.result.emit(result)
        except Exception as e:
            self.error.emit(str(e))
        finally:
            self.finished_signal.emit()   # ← دائماً يشتغل


class WAFDetectorWidget(QWidget):
    status_update = pyqtSignal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.worker = None
        self.setup_ui()
        self.connect_signals()

    def setup_ui(self):
        layout = QVBoxLayout(self)

        input_layout = QHBoxLayout()
        self.target_input = QLineEdit()
        self.target_input.setPlaceholderText("example.com or https://example.com")
        self.detect_btn = QPushButton("Detect")
        self.stop_btn = QPushButton("Stop")
        self.stop_btn.setEnabled(False)
        input_layout.addWidget(self.target_input)
        input_layout.addWidget(self.detect_btn)
        input_layout.addWidget(self.stop_btn)
        layout.addLayout(input_layout)

        self.progress_bar = QProgressBar()
        self.progress_label = QLabel("Ready")
        layout.addWidget(self.progress_bar)
        layout.addWidget(self.progress_label)

        self.result_group = QGroupBox("Detection Result")
        result_layout = QVBoxLayout()
        self.waf_label = QLabel("WAF: --")
        self.cdn_label = QLabel("CDN: --")
        self.confidence_bar = QProgressBar()
        self.confidence_bar.setRange(0, 100)
        self.verdict_label = QLabel("Verdict: --")
        result_layout.addWidget(self.waf_label)
        result_layout.addWidget(self.cdn_label)
        result_layout.addWidget(QLabel("Confidence:"))
        result_layout.addWidget(self.confidence_bar)
        result_layout.addWidget(self.verdict_label)
        self.result_group.setLayout(result_layout)
        layout.addWidget(self.result_group)

        self.indicators_table = QTableWidget()
        self.indicators_table.setColumnCount(2)
        self.indicators_table.setHorizontalHeaderLabels(["Indicator", "Matched Value"])
        self.indicators_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        layout.addWidget(QLabel("Matched Indicators:"))
        layout.addWidget(self.indicators_table)

        self.tips_text = QTextEdit()
        self.tips_text.setReadOnly(True)
        self.tips_text.setMaximumHeight(150)
        layout.addWidget(QLabel("Evasion Tips:"))
        layout.addWidget(self.tips_text)

        self.setLayout(layout)

    def connect_signals(self):
        self.detect_btn.clicked.connect(self.start_detection)
        self.stop_btn.clicked.connect(self.stop_detection)

    def start_detection(self):
        target = self.target_input.text().strip()
        # ✓ التحقق أولاً من وجود قيمة
        if not target:
            QMessageBox.warning(self, "No Target", "Please enter a URL or domain.")
            return
        # ✓ ثم إضافة البروتوكول إذا كان مفقوداً
        if not target.startswith(('http://', 'https://')):
            target = 'https://' + target

        self.worker = WAFDetectWorker(target)
        self.worker.progress.connect(self.on_progress)
        self.worker.result.connect(self.display_result)
        self.worker.error.connect(self.on_worker_error)
        self.worker.finished_signal.connect(self._on_detection_finished)
        self.worker.start()

        self.detect_btn.setEnabled(False)
        self.stop_btn.setEnabled(True)
        self.progress_bar.setValue(0)
        self.status_update.emit(f"Detection started for {target}...")

    def stop_detection(self):
        if self.worker:
            self.worker.abort()
        # لا نعيد تمكين الأزرار هنا مباشرة، بل ننتظر إشارة finished_signal
        self.status_update.emit("Detection stopped by user.")

    def on_progress(self, percent: int, message: str):
        self.progress_bar.setValue(percent)
        self.progress_label.setText(message)

    def on_worker_error(self, err_msg: str):
        self.status_update.emit(f"Error: {err_msg}")
        QMessageBox.critical(self, "Detection Error", err_msg)

    def _on_detection_finished(self):
        """إعادة تمكين الأزرار بعد انتهاء المسح (سواء نجح أو فشل)"""
        self.detect_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)

    def display_result(self, result: dict):
        self.waf_label.setText(f"WAF: {result['waf_name']}")
        self.cdn_label.setText(f"CDN: {result['cdn']}")
        self.confidence_bar.setValue(result['confidence'])
        self.verdict_label.setText(f"Verdict: {result['verdict']} ({result['confidence']}%)")
        self.indicators_table.setRowCount(len(result['indicators']))
        for row, ind in enumerate(result['indicators']):
            parts = ind.split(':', 1)
            self.indicators_table.setItem(row, 0, QTableWidgetItem(parts[0] if parts else ind))
            self.indicators_table.setItem(row, 1, QTableWidgetItem(parts[1] if len(parts) > 1 else ''))
        self.tips_text.setText(result['evasion_tips'])
        self.status_update.emit(f"Detection completed: {result['waf_name']} with {result['confidence']}% confidence")

    def get_module_name(self) -> str:
        return "WAF/CDN Detector"
