#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Image Metadata OSINT - Rich metadata (exiftool or PIL), AI detection, and full PDF report.
"""

import json
import logging
import subprocess
import shutil
from pathlib import Path
from datetime import datetime
from PIL import Image, ExifTags
import numpy as np
from PyQt6.QtCore import Qt, QUrl, pyqtSignal, QThread
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QLineEdit,
    QLabel, QTabWidget, QTableWidget, QTableWidgetItem, QHeaderView,
    QFileDialog, QMessageBox, QApplication, QProgressBar
)
from PyQt6.QtGui import QPixmap, QDesktopServices

from core.event_bus import EventBus

logger = logging.getLogger(__name__)


# ----------------------------------------------------------------------
# Helper functions for AI detection (same as before, but kept)
# ----------------------------------------------------------------------
def compute_entropy(image_path: str) -> float:
    try:
        img = Image.open(image_path).convert('L')
        pixels = np.array(img).flatten()
        hist = np.histogram(pixels, bins=256, range=(0, 256))[0]
        hist = hist / hist.sum()
        entropy = -np.sum(hist * np.log2(hist + 1e-10))
        return entropy
    except:
        return 0.0


def detect_ai(image_path: str, metadata: dict) -> tuple:
    reasons = []
    confidence = 0.0
    ai_keywords = {
        "Software": ["midjourney", "dall-e", "stable diffusion", "adobe firefly", "leonardo ai",
                     "playground ai", "nightcafe", "deepai", "craiyon", "wombo", "dream"],
        "Description": ["ai generated", "artificial intelligence", "prompt", "generated by"],
        "Copyright": ["ai", "generated"],
        "Creator": ["ai", "generated"],
        "Artist": ["ai", "generated"],
        "Make": ["ai"],
        "Model": ["dall-e", "midjourney", "stable diffusion"],
        "XMP:CreatorTool": ["midjourney", "dall-e", "stable diffusion"],
        "XMP:Generator": ["ai"],
        "XMP:Manifest": ["ai"],
        "Exif:ImageDescription": ["ai generated"]
    }
    for field, patterns in ai_keywords.items():
        if field in metadata:
            val = str(metadata[field]).lower()
            for pat in patterns:
                if pat in val:
                    reasons.append(f"{field}: '{pat}'")
                    confidence += 0.25
                    break
    has_camera_make = any(f in metadata for f in ["Make", "Model", "GPSInfo", "GPSLatitude"])
    if not has_camera_make:
        reasons.append("Missing typical camera EXIF (Make/Model/GPS)")
        confidence += 0.2
    entropy = compute_entropy(image_path)
    if entropy > 7.5:
        reasons.append(f"High image entropy ({entropy:.2f}) - typical of AI generation")
        confidence += 0.25
    elif entropy < 5.0:
        reasons.append(f"Low image entropy ({entropy:.2f}) - possibly simple graphics")
        confidence -= 0.1
    confidence = max(0.0, min(1.0, confidence))
    is_ai = confidence >= 0.4
    return is_ai, confidence, reasons


# ----------------------------------------------------------------------
# Worker with rich metadata extraction (exiftool preferred, then PIL+)
# ----------------------------------------------------------------------
class MetadataExtractWorker(QThread):
    metadata_ready = pyqtSignal(dict)
    ai_detection_result = pyqtSignal(bool, float, list)
    sensitive_found = pyqtSignal(str, str)
    finished = pyqtSignal()
    error = pyqtSignal(str)

    def __init__(self, filepath: str):
        super().__init__()
        self.filepath = filepath
        self._abort = False

    def abort(self):
        self._abort = True

    def run(self):
        try:
            metadata = {}
            # Prefer exiftool for maximum details
            exiftool = shutil.which('exiftool')
            if exiftool:
                try:
                    proc = subprocess.run(
                        [exiftool, '-j', '-n', self.filepath],
                        capture_output=True, text=True, timeout=30
                    )
                    if proc.returncode == 0 and proc.stdout.strip():
                        metadata = json.loads(proc.stdout)[0]
                    else:
                        logger.warning("exiftool returned no data, falling back to PIL")
                except Exception as e:
                    logger.warning(f"exiftool error: {e}, falling back to PIL")
            # If exiftool failed or not installed, use PIL + file info
            if not metadata:
                img = Image.open(self.filepath)
                exif = img._getexif()
                if exif:
                    for tag_id, value in exif.items():
                        tag_name = ExifTags.TAGS.get(tag_id, tag_id)
                        metadata[tag_name] = str(value)
                # Add essential file info
                stat = Path(self.filepath).stat()
                metadata["FileType"] = img.format or "Unknown"
                metadata["ImageSize"] = f"{img.width}x{img.height}"
                metadata["FileSize"] = f"{stat.st_size} bytes"
                metadata["LastModified"] = datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M:%S")
            # Emit rich metadata
            self.metadata_ready.emit(metadata)
            if self._abort:
                return

            # AI detection
            is_ai, conf, reasons = detect_ai(self.filepath, metadata)
            self.ai_detection_result.emit(is_ai, conf, reasons)
            if self._abort:
                return

            # Sensitive data detection (using common sensitive fields)
            sensitive_fields = [
                'Artist', 'Author', 'OwnerName', 'Creator', 'Copyright',
                'GPSLatitude', 'GPSLongitude', 'GPSAltitude', 'GPSInfo',
                'SerialNumber', 'CreateDate', 'ModifyDate', 'DateTimeOriginal',
                'XPComment', 'XPAuthor', 'XPKeywords', 'XPSubject'
            ]
            for field in sensitive_fields:
                if field in metadata and metadata[field]:
                    self.sensitive_found.emit(field, str(metadata[field])[:200])
            self.finished.emit()
        except Exception as e:
            self.error.emit(str(e))


# ----------------------------------------------------------------------
# Main Widget
# ----------------------------------------------------------------------
class ImageMetadataWidget(QWidget):
    status_update = pyqtSignal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.worker = None
        self.setup_ui()
        self.current_metadata = {}

    def setup_ui(self):
        layout = QVBoxLayout(self)

        # Input area
        input_layout = QHBoxLayout()
        self.file_path = QLineEdit()
        self.browse_btn = QPushButton("Browse")
        self.analyze_btn = QPushButton("Analyze")
        input_layout.addWidget(self.file_path)
        input_layout.addWidget(self.browse_btn)
        input_layout.addWidget(self.analyze_btn)
        layout.addLayout(input_layout)

        # Thumbnail and tabs
        content = QHBoxLayout()
        self.thumbnail_label = QLabel()
        self.thumbnail_label.setFixedSize(300, 300)
        self.thumbnail_label.setStyleSheet("border: 1px solid #30363D; background-color: #161B22;")
        content.addWidget(self.thumbnail_label)

        self.tabs = QTabWidget()

        # Tab 1: All Metadata (rich)
        self.metadata_table = QTableWidget()
        self.metadata_table.setColumnCount(2)
        self.metadata_table.setHorizontalHeaderLabels(["Field", "Value"])
        self.metadata_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.tabs.addTab(self.metadata_table, "All Metadata")

        # Tab 2: AI Detection
        self.ai_tab = QWidget()
        ai_layout = QVBoxLayout(self.ai_tab)
        self.ai_card = QWidget()
        self.ai_card.setStyleSheet("background-color: #1C2128; border-radius: 12px; padding: 15px;")
        card_layout = QVBoxLayout(self.ai_card)
        self.ai_status_label = QLabel()
        self.ai_status_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ai_status_label.setStyleSheet("font-size: 18px; font-weight: bold;")
        card_layout.addWidget(self.ai_status_label)
        self.ai_confidence_bar = QProgressBar()
        self.ai_confidence_bar.setRange(0, 100)
        self.ai_confidence_bar.setFormat("%p%")
        card_layout.addWidget(self.ai_confidence_bar)
        self.ai_reasons_label = QLabel()
        self.ai_reasons_label.setWordWrap(True)
        self.ai_reasons_label.setStyleSheet("color: #8B949E; margin-top: 10px;")
        card_layout.addWidget(self.ai_reasons_label)
        ai_layout.addWidget(self.ai_card)
        self.tabs.addTab(self.ai_tab, "🤖 AI Detection")

        # Tab 3: Sensitive Data
        self.sensitive_text = QLabel()
        self.sensitive_text.setWordWrap(True)
        self.sensitive_text.setStyleSheet("padding: 10px;")
        self.tabs.addTab(self.sensitive_text, "Sensitive Data")

        content.addWidget(self.tabs)
        layout.addLayout(content)

        # Toolbar
        toolbar = QHBoxLayout()
        self.reverse_btn = QPushButton("Reverse Image Search")
        self.save_notes_btn = QPushButton("Save to Notes")
        self.export_html_btn = QPushButton("Export HTML")
        self.export_pdf_btn = QPushButton("Export PDF")
        toolbar.addWidget(self.reverse_btn)
        toolbar.addWidget(self.save_notes_btn)
        toolbar.addWidget(self.export_html_btn)
        toolbar.addWidget(self.export_pdf_btn)
        layout.addLayout(toolbar)

        self.status_label = QLabel("Ready")
        layout.addWidget(self.status_label)

        # Signals
        self.browse_btn.clicked.connect(self.browse)
        self.analyze_btn.clicked.connect(self.analyze)
        self.reverse_btn.clicked.connect(self.reverse_search)
        self.save_notes_btn.clicked.connect(self.save_to_notes)
        self.export_html_btn.clicked.connect(self.export_html)
        self.export_pdf_btn.clicked.connect(self.export_pdf)

    def browse(self):
        path, _ = QFileDialog.getOpenFileName(self, "Select Image or File", "",
                                              "Image Files (*.png *.jpg *.jpeg *.tiff *.bmp);;All Files (*)")
        if path:
            self.file_path.setText(path)
            pixmap = QPixmap(path)
            if not pixmap.isNull():
                self.thumbnail_label.setPixmap(pixmap.scaled(300, 300, Qt.AspectRatioMode.KeepAspectRatio))
            else:
                self.thumbnail_label.setText("Not an image")

    def analyze(self):
        path = self.file_path.text().strip()
        if not path or not Path(path).exists():
            QMessageBox.warning(self, "No File", "Please select a file.")
            return
        if self.worker and self.worker.isRunning():
            self.worker.abort()
        self.worker = MetadataExtractWorker(path)
        self.worker.metadata_ready.connect(self.display_metadata)
        self.worker.ai_detection_result.connect(self.display_ai_detection)
        self.worker.sensitive_found.connect(self.add_sensitive)
        self.worker.finished.connect(self.on_finished)
        self.worker.error.connect(self.on_error)
        self.worker.start()
        self.status_label.setText("Extracting metadata...")
        self.sensitive_text.clear()
        self.ai_status_label.setText("Analyzing...")
        self.ai_confidence_bar.setValue(0)
        self.ai_reasons_label.setText("")
        self.current_metadata = {}

    def display_metadata(self, data: dict):
        self.current_metadata = data
        self.metadata_table.setRowCount(len(data))
        for row, (k, v) in enumerate(data.items()):
            self.metadata_table.setItem(row, 0, QTableWidgetItem(str(k)))
            self.metadata_table.setItem(row, 1, QTableWidgetItem(str(v)[:500]))

    def display_ai_detection(self, is_ai: bool, confidence: float, reasons: list):
        conf_percent = int(confidence * 100)
        self.ai_confidence_bar.setValue(conf_percent)
        if is_ai:
            self.ai_status_label.setText("⚠️ LIKELY AI‑GENERATED IMAGE")
            self.ai_status_label.setStyleSheet("color: #FF4D4D; font-size: 18px; font-weight: bold;")
            self.ai_card.setStyleSheet("background-color: #1C2128; border-left: 6px solid #FF4D4D; border-radius: 12px; padding: 15px;")
        else:
            self.ai_status_label.setText("✅ LIKELY REAL / CAMERA‑CAPTURED")
            self.ai_status_label.setStyleSheet("color: #00FF9C; font-size: 18px; font-weight: bold;")
            self.ai_card.setStyleSheet("background-color: #1C2128; border-left: 6px solid #00FF9C; border-radius: 12px; padding: 15px;")
        if reasons:
            self.ai_reasons_label.setText("🔍 INDICATORS:\n• " + "\n• ".join(reasons[:5]))
        else:
            self.ai_reasons_label.setText("No strong AI indicators found.")

    def add_sensitive(self, field: str, value: str):
        current = self.sensitive_text.text()
        if current:
            self.sensitive_text.setText(f"{current}\n⚠️ {field}: {value}")
        else:
            self.sensitive_text.setText(f"⚠️ {field}: {value}")
        self.sensitive_text.setStyleSheet("color: #FF4D4D; background-color: #1C2128; padding: 10px;")

    def on_finished(self):
        self.status_label.setText("Analysis completed.")
        self.status_update.emit("Image metadata analysis completed.")
        self.worker = None

    def on_error(self, err: str):
        self.status_label.setText(f"Error: {err}")
        self.status_update.emit(f"Metadata error: {err}")
        QMessageBox.critical(self, "Analysis Error", err)
        self.worker = None

    def reverse_search(self):
        QDesktopServices.openUrl(QUrl("https://images.google.com/"))

    def save_to_notes(self):
        report = self._generate_markdown()
        EventBus().send_to_notes.emit(f"# Image Metadata Report\n\n{report}")
        self.status_update.emit("Sent to Notes.")

    def _generate_markdown(self) -> str:
        return f"**File:** {self.file_path.text()}\n\n**AI Detection:** {self.ai_status_label.text()}\n**Confidence:** {self.ai_confidence_bar.value()}%\n\n**Indicators:**\n{self.ai_reasons_label.text()}\n\n**Sensitive Data:**\n{self.sensitive_text.text()}"

    def export_html(self):
        path, _ = QFileDialog.getSaveFileName(self, "Save HTML", "metadata_report.html", "HTML (*.html)")
        if path:
            html = self._generate_html()
            Path(path).write_text(html, encoding='utf-8')
            self.status_update.emit(f"Saved to {path}")

    def export_pdf(self):
        from weasyprint import HTML
        path, _ = QFileDialog.getSaveFileName(self, "Save PDF", "metadata_report.pdf", "PDF (*.pdf)")
        if not path:
            return
        try:
            HTML(string=self._generate_html()).write_pdf(path)
            self.status_update.emit(f"PDF saved to {path}")
        except Exception as e:
            QMessageBox.critical(self, "Export Error", str(e))

    def _generate_html(self) -> str:
        # Build All Metadata table rows
        rows = ""
        for row in range(self.metadata_table.rowCount()):
            field = self.metadata_table.item(row, 0).text()
            value = self.metadata_table.item(row, 1).text()
            rows += f"<tr><td style='border:1px solid #ddd;padding:6px;'><strong>{field}</strong></td><td style='border:1px solid #ddd;padding:6px;'>{value}</td></tr>"

        # AI detection results
        ai_status = self.ai_status_label.text()
        ai_conf = self.ai_confidence_bar.value()
        ai_reasons = self.ai_reasons_label.text().replace('\n', '<br>')

        # Sensitive data
        sensitive = self.sensitive_text.text().replace('\n', '<br>')

        html = f"""
        <!DOCTYPE html>
        <html>
        <head><meta charset="UTF-8"><title>Image Metadata Report</title>
        <style>
            body {{ font-family: sans-serif; margin: 2em; }}
            h1, h2 {{ color: #00FF9C; }}
            table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f2f2f2; }}
            .ai-true {{ color: #FF4D4D; font-weight: bold; }}
            .ai-false {{ color: #00FF9C; font-weight: bold; }}
            .indicator {{ background-color: #1C2128; padding: 10px; border-radius: 5px; }}
        </style>
        </head>
        <body>
        <h1>📸 Image Metadata Report</h1>
        <p><strong>File:</strong> {self.file_path.text()}</p>

        <h2>🤖 AI Detection</h2>
        <div><strong>Result:</strong> <span class="{'ai-true' if 'AI' in ai_status else 'ai-false'}">{ai_status}</span></div>
        <div><strong>Confidence:</strong> {ai_conf}%</div>
        <div class="indicator"><strong>Indicators:</strong><br>{ai_reasons}</div>

        <h2>📋 All Metadata</h2>
        <table>
            <thead><tr><th>Field</th><th>Value</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>

        <h2>⚠️ Sensitive Data</h2>
        <div class="indicator">{sensitive}</div>
        </body>
        </html>
        """
        return html

    def get_module_name(self) -> str:
        return "Image Metadata"
